FROM nginx:alpine

# Expose port 8080 for Cloud Run
EXPOSE 8080

# Update nginx.conf to listen on port 8080
RUN sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/conf.d/default.conf

# Create a directory for the mount point
RUN mkdir -p /etc/nginx/external-conf

# Copy the external config *before* starting nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

