version = "v24.0"
message1 = "first message"
Temperature = 1
Lastrefreshdate = "04 Apr 2025"
disclaimer_message = "AIGard is not the official compliance software of the EU AI Act. The recommendations provided by our software should not be interpreted in a legally binding context of the act.  We are constantly trying to improve the accuracy of our recommendations.  We make a best effort to check against the Regulation and Directives, Articles, Annexes and Recitals within the EU AI Act that is applicable to your context.  It is advised to get a legal advise to comply to the Act."
release_version = "v26-20250411-12:57"
BASE_URL_COMPANY_SEARCH = "https://api.company-information.service.gov.uk/company/{company_number}"